# This will be used for errors in the console and as a fallback when a user's language isn't on the server.
default-locale: "en-US"

# The RTP menu's title.
# You can change the menu's texture with it and ItemsAdder or Nexo (read their respective wikis if you don't know how)
menu-title: "<#45CC4B>RTP Menu"

# Previous and next page items. Doesn't matter if you have 3 or fewer worlds.
# You can use ItemsAdder items by changing this to itemsadder-namespace:itemname (example: itemsadder-customitems:coolstick)
# Or you can use Nexo items by changing this to nexo-itemname (example: nexo-coolstick)
previous-page-item: arrow
next-page-item: arrow

# Allows or denies teleporting inside towns or outposts, works only with Towny
allow-rtp-in-towns: false
allow-rtp-in-outposts: false

# Allows or denies teleporting inside areas protected by GriefPrevention
allow-rtp-in-griefprevention: false

# Cooldown between RTP usages. Default is 10 seconds.
rtp-cooldown: 10
# Allows having separate cooldowns for every world.
per-world-cooldowns: true